### ISSUE TITLE
Remove react and react-native as a dependency

### ISSUE THREAD

**Issue by hasseio** [Streemo/react-ddp#1]
I was wondering why I was getting two copies of react-native in my tree :)

**Comment by Streemo** [comment]
This codebase requires `react-native`, since we are using `AsyncStorage`. Should we instead list it as a peer dependency? Alternatively, we could relax the version constraint for `react-native`, in which case installing `react-ddp` will not result in a new version of `react-native` also being installed.

**Comment by hasseio** [comment]
A peer dependency for react-native with a relaxed semver sounds good.

**Comment by Streemo** [comment]
React and React Native are now `peerDependencies`. Let me know if there are any problems! Thanks. Closing this for now.
